'use strict';

var path = require('path');

module.exports = {
  name: 'ember-cli-famous',

  included: function(app) {
    this.app = app;

    // List of exports provided from:
    // https://github.com/Famous/famous-angular/blob/master/src/scripts/services/famous.js#L10-L106
    app.import(path.join(app.bowerDirectory, 'famous', 'dist', 'famous.js'), {
      exports: {
        'famous/core/Context':                         'default',
        'famous/core/ElementAllocator':                'default',
        'famous/core/Engine':                          'default',
        'famous/core/Entity':                          'default',
        'famous/core/EventEmitter':                    'default',
        'famous/core/EventHandler':                    'default',
        'famous/core/Group':                           'default',
        'famous/core/Modifier':                        'default',
        'famous/core/OptionsManager':                  'default',
        'famous/core/RenderNode':                      'default',
        'famous/core/Scene':                           'default',
        'famous/core/SpecParser':                      'default',
        'famous/core/Surface':                         'default',
        'famous/core/Transform':                       'default',
        'famous/core/View':                            'default',
        'famous/core/ViewSequence':                    'default',
        'famous/events/EventArbiter':                  'default',
        'famous/events/EventFilter':                   'default',
        'famous/events/EventMapper':                   'default',
        'famous/inputs/FastClick':                     'default',
        'famous/inputs/GenericSync':                   'default',
        'famous/inputs/MouseSync':                     'default',
        'famous/inputs/PinchSync':                     'default',
        'famous/inputs/RotateSync':                    'default',
        'famous/inputs/ScaleSync':                     'default',
        'famous/inputs/ScrollSync':                    'default',
        'famous/inputs/TouchSync':                     'default',
        'famous/inputs/TouchTracker':                  'default',
        'famous/inputs/TwoFingerSync':                 'default',
        'famous/math/Matrix':                          'default',
        'famous/math/Quaternion':                      'default',
        'famous/math/Random':                          'default',
        'famous/math/Utilities':                       'default',
        'famous/math/Vector':                          'default',
        'famous/modifiers/Draggable':                  'default',
        'famous/modifiers/Fader':                      'default',
        'famous/modifiers/ModifierChain':              'default',
        'famous/modifiers/StateModifier':              'default',
        'famous/surfaces/CanvasSurface':               'default',
        'famous/surfaces/ContainerSurface':            'default',
        'famous/surfaces/FormContainerSurface':        'default',
        'famous/surfaces/ImageSurface':                'default',
        'famous/surfaces/InputSurface':                'default',
        'famous/surfaces/SubmitInputSurface':          'default',
        'famous/surfaces/TextareaSurface':             'default',
        'famous/surfaces/VideoSurface':                'default',
        'famous/transitions/CachedMap':                'default',
        'famous/transitions/Easing':                   'default',
        'famous/transitions/MultipleTransition':       'default',
        'famous/transitions/SnapTransition':           'default',
        'famous/transitions/SpringTransition':         'default',
        'famous/transitions/Transitionable':           'default',
        'famous/transitions/TransitionableTransform':  'default',
        'famous/transitions/TweenTransition':          'default',
        'famous/transitions/WallTransition':           'default',
        'famous/utilities/KeyCodes':                   'default',
        'famous/utilities/Timer':                      'default',
        'famous/utilities/Utility':                    'default',
        'famous/views/Deck':                           'default',
        'famous/views/EdgeSwapper':                    'default',
        'famous/views/FlexibleLayout':                 'default',
        'famous/views/Flipper':                        'default',
        'famous/views/GridLayout':                     'default',
        'famous/views/HeaderFooterLayout':             'default',
        'famous/views/Lightbox':                       'default',
        'famous/views/RenderController':               'default',
        'famous/views/ScrollContainer':                'default',
        'famous/views/Scroller':                       'default',
        'famous/views/Scrollview':                     'default',
        'famous/views/SequentialLayout':               'default',
        'famous/widgets/NavigationBar':                'default',
        'famous/widgets/Slider':                       'default',
        'famous/widgets/TabBar':                       'default',
        'famous/widgets/ToggleButton':                 'default',
        'famous/physics/PhysicsEngine':                'default',
        'famous/physics/bodies/Body':                  'default',
        'famous/physics/bodies/Circle':                'default',
        'famous/physics/bodies/Particle':              'default',
        'famous/physics/bodies/Rectangle':             'default',
        'famous/physics/constraints/Collision':        'default',
        'famous/physics/constraints/Constraint':       'default',
        'famous/physics/constraints/Curve':            'default',
        'famous/physics/constraints/Distance':         'default',
        'famous/physics/constraints/Snap':             'default',
        'famous/physics/constraints/Surface':          'default',
        'famous/physics/constraints/Wall':             'default',
        'famous/physics/constraints/Walls':            'default',
        'famous/physics/forces/Drag':                  'default',
        'famous/physics/forces/Force':                 'default',
        'famous/physics/forces/Repulsion':             'default',
        'famous/physics/forces/RotationalDrag':        'default',
        'famous/physics/forces/RotationalSpring':      'default',
        'famous/physics/forces/Spring':                'default',
        'famous/physics/forces/VectorField':           'default',
        'famous/physics/integrators/SymplecticEuler':  'default'
      }
    });
  }
};
